### ISSUE TITLE
Does not work if authority is changed to *.b2clogin.com

### ISSUE THREAD

**Issue by kaushikgayal** [AzureADQuickStarts/B2C-GraphAPI-DotNet#19]
It works perfectly fine with authority as login.microsoftonline.com but when authority is changed to b2clogin.com. It throws an exception.
I tried upgrading AD nuget to the latest version 5.1 and also updated code to set Validate Authority to false.
Still fails.

**Comment by Visinghr** [comment]
@kaushikgayal  it is not needed to use b2clogin.com domain because this is sample, we have used the client credentials flow, which is inherited capability of the enterprise tenant.  I think, you are worried about deprecated of login.microsoft.com domain for b2c Tenant, flow in this sample is not going to be affected. ref this - https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin#endpoints-that-are-not-affected

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
