### ISSUE TITLE
Stop using a v1 app to make Graph calls

### ISSUE THREAD

**Issue by dstrockis** [AzureADQuickStarts/B2C-GraphAPI-DotNet#8]
Just use the B2C app itself

**Comment by llumpu** [comment]
Do I understand, that instead of creating app in AD via powershell as being mentoied in many tutorials and docs is possible to use already created and used B2C extension app which already has access to AD? I have finished small app which uses Azure Mobile App and Android client protected by Azure AD B2C and got interested in calling AD Graph API from this Azure Mobile App backend written in .NET. Now I came here and see that You suggest not using v1 app which I understand is the one created using powershell tool? So as I understand I have to use AppID and Key from ADB2C extension app to get token from AD Graph API?

So is this possible to use this in Azure Mobile App? Do I need to use library ADAL to authenticate with AppID and key from B2C extension app? There is not much info for one using Azure Mobile App backend in .NET.

**Comment by JimBobSquarePants** [comment]
> Just use the B2C app itself

@dstrockis Could you possible clarify what you mean by this with example code?

**Comment by gsacavdm** [comment]
There is no example code because this is not currently possible. Once the feature is delivered, the code sample would be simplified and this issue closed.

**Comment by JimBobSquarePants** [comment]
Ah ok, makes sense. Thanks!

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
